ARDUINO_DIR = /usr/share/arduino

TARGET = tcl
ARDUINO_LIBS = SPI TCL

#BOARD_TAG    = atmega328
BOARD_TAG    = uno
#ARDUINO_PORT = /dev/ttyUSB0
ARDUINO_PORT = /dev/ttyACM0

include /home/stepcut/n-heptane/projects/arduino/Arduino-Makefile/Arduino.mk

.PHONY: upload
